In [2]:
import pandas as pd

In [3]:
mandates_n_creds = pd.read_csv("main_cleaned.csv-mandates-credits.csv")
loan_disk = pd.read_csv("all2 - Copy.csv")

In [4]:
# list(loan_disk.columns)

In [5]:
mandates_n_creds.drop(["Unnamed: 0"], axis = 1, inplace = True) # drop the unwanted column Unnamed: 0 from mandates

In [6]:
mandates_n_creds.columns = ['mandates_bank', ' CREDIT'] # rename mandates to mandates_bank

In [7]:
required_columns = ['loan_id',
                     'loan_principal_amount',
                     'loan_released_date',
                     'total_amount_due',
                     'balance_amount',
                     'due_date',
                     'total_paid',
                     'custom_field_4361',
                     'custom_field_4178',
                     'custom_field_5262',
                     'borrower_firstname',
                     'borrower_lastname',
                     'borrower_email',
                     'borrower_address',
                     ]
loan_disk_target = loan_disk[required_columns]

In [8]:
required_columns_customized = ['loan_id',
                                 'loan_principal_amount',
                                 'loan_released_date',
                                 'total_amount_due',
                                 'balance_amount',
                                 'due_date',
                                 'total_paid',
                                 'bvn',
                                 'account_no',
                                 'mandates_loandisk',
                                 'borrower_firstname',
                                 'borrower_lastname',
                                 'borrower_email',
                                 'borrower_address',
                                 ]

loan_disk_target.columns = required_columns_customized # change  certain column names in the fields

In [9]:
loan_disk_target

,loan_id,loan_principal_amount,loan_released_date,total_amount_due,balance_amount,due_date,total_paid,bvn,account_no,mandates_loandisk,borrower_firstname,borrower_lastname,borrower_email,borrower_address
0,1369069,40000,24/05/2020,NaN,0.00,31/05/2020,50000.00,22155117727,58578850,1.803991e+11,DIAMOND,UDOIDIONG,diamondray943@gmail.com,NATIONAL OIL SPILL DETECTION AND RESPONSE AGENCY
1,1369070,40000,24/05/2020,NaN,20472.64,31/05/2020,29527.36,22248314110,3280263014,1.403991e+11,KENNETH,ONWORDI,talk2sirnd@yahoo.com,FEDERAL MINISTRY OF INFORMATION & CULTURE - HQTRS
2,1369071,30000,24/05/2020,NaN,0.00,31/05/2020,37500.00,22264860545,23357418,1.503991e+11,OLUWASEUN,FAYOMI,fayomiooseun@yahoo.com,MEDICAL AND DENTAL COUNCIL OF NIGERIA
3,1369072,30000,25/05/2020,NaN,0.00,31/05/2020,37500.00,22224174907,39798746,3.403993e+11,charles,udogwu,NaN,"FEDERAL MEDICAL CENTRE, EBUTE METTA"
4,1369073,10000,25/05/2020,NaN,0.00,31/05/2020,12500.00,22211157144,2016781863,1.503993e+11,JAMES,ARONI,jamesenders007@gmail.com,NATIONAL YOUTH SERVICE CORPS (NYSC)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12336,1944895,12500,13/04/2021,NaN,16625.00,13/05/2021,0.00,22188539770,3012996918,1.404791e+11,olagoke,olubodun,noemail@email.com,OLUBODUN - OLAGOKE
12337,1944896,7000,13/04/2021,NaN,9310.00,13/05/2021,0.00,22193249987,9886404,1.004791e+11,rasaq,oyekanmi,noemail@email.com,NATIONAL DIRECTORATE OF EMPLOYMENT
12338,1944949,17000,13/04/2021,NaN,22610.00,13/05/2021,0.00,22248813253,25324261,1.504792e+11,shakaa,greater,noemail@email.com,GREATER CALLISTUS SHAKAA
12339,1944986,3750,13/04/2021,NaN,4990.00,13/05/2021,0.00,22264692555,2746701015,3.404792e+11,adamu,mohammed,NaN,GOMBE STATE LGA SALARY
12340,1944989,6000,13/04/2021,NaN,7980.00,13/05/2021,0.00,22207075348,3741041014,2.704792e+11,wahab,bello,noemail@email.com,PUBLIC COMPLAINTS COMMISSION

In [10]:
pd.merge(
         left = loan_disk_target, 
         right=mandates_n_creds, 
         how="outer", 
         left_on="mandates_loandisk", 
         right_on="mandates_bank"
        )

,loan_id,loan_principal_amount,loan_released_date,total_amount_due,balance_amount,due_date,total_paid,bvn,account_no,mandates_loandisk,borrower_firstname,borrower_lastname,borrower_email,borrower_address,mandates_bank,CREDIT
0,1369069.0,40000.0,24/05/2020,NaN,0.00,31/05/2020,50000.00,2.215512e+10,5.857885e+07,1.803991e+11,DIAMOND,UDOIDIONG,diamondray943@gmail.com,NATIONAL OIL SPILL DETECTION AND RESPONSE AGENCY,1.803991e+11,50000.00
1,1369070.0,40000.0,24/05/2020,NaN,20472.64,31/05/2020,29527.36,2.224831e+10,3.280263e+09,1.403991e+11,KENNETH,ONWORDI,talk2sirnd@yahoo.com,FEDERAL MINISTRY OF INFORMATION & CULTURE - HQTRS,1.403991e+11,29378.93
2,1369071.0,30000.0,24/05/2020,NaN,0.00,31/05/2020,37500.00,2.226486e+10,2.335742e+07,1.503991e+11,OLUWASEUN,FAYOMI,fayomiooseun@yahoo.com,MEDICAL AND DENTAL COUNCIL OF NIGERIA,1.503991e+11,37500.00
3,1369072.0,30000.0,25/05/2020,NaN,0.00,31/05/2020,37500.00,2.222417e+10,3.979875e+07,3.403993e+11,charles,udogwu,NaN,"FEDERAL MEDICAL CENTRE, EBUTE METTA",3.403993e+11,37500.00
4,1369073.0,10000.0,25/05/2020,NaN,0.00,31/05/2020,12500.00,2.221116e+10,2.016782e+09,1.503993e+11,JAMES,ARONI,jamesenders007@gmail.com,NATIONAL YOUTH SERVICE CORPS (NYSC),1.503993e+11,12500.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12503,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.404668e+11,13300.00
12504,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.503991e+11,1.00
12505,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.504338e+11,11970.00
12506,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.504404e+11,6650.00
12507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.504621e+11,7980.00

In [11]:
merged = pd.merge(
                 left = loan_disk_target, 
                 right=mandates_n_creds, 
                 how="outer", 
                 left_on="mandates_loandisk", 
                 right_on="mandates_bank"
                 )

In [12]:
credit_difference = merged.total_paid - merged[" CREDIT"]
merged["credit_difference"] = credit_difference

In [13]:
merged

,loan_id,loan_principal_amount,loan_released_date,total_amount_due,balance_amount,due_date,total_paid,bvn,account_no,mandates_loandisk,borrower_firstname,borrower_lastname,borrower_email,borrower_address,mandates_bank,CREDIT,credit_difference
0,1369069.0,40000.0,24/05/2020,NaN,0.00,31/05/2020,50000.00,2.215512e+10,5.857885e+07,1.803991e+11,DIAMOND,UDOIDIONG,diamondray943@gmail.com,NATIONAL OIL SPILL DETECTION AND RESPONSE AGENCY,1.803991e+11,50000.00,0.00
1,1369070.0,40000.0,24/05/2020,NaN,20472.64,31/05/2020,29527.36,2.224831e+10,3.280263e+09,1.403991e+11,KENNETH,ONWORDI,talk2sirnd@yahoo.com,FEDERAL MINISTRY OF INFORMATION & CULTURE - HQTRS,1.403991e+11,29378.93,148.43
2,1369071.0,30000.0,24/05/2020,NaN,0.00,31/05/2020,37500.00,2.226486e+10,2.335742e+07,1.503991e+11,OLUWASEUN,FAYOMI,fayomiooseun@yahoo.com,MEDICAL AND DENTAL COUNCIL OF NIGERIA,1.503991e+11,37500.00,0.00
3,1369072.0,30000.0,25/05/2020,NaN,0.00,31/05/2020,37500.00,2.222417e+10,3.979875e+07,3.403993e+11,charles,udogwu,NaN,"FEDERAL MEDICAL CENTRE, EBUTE METTA",3.403993e+11,37500.00,0.00
4,1369073.0,10000.0,25/05/2020,NaN,0.00,31/05/2020,12500.00,2.221116e+10,2.016782e+09,1.503993e+11,JAMES,ARONI,jamesenders007@gmail.com,NATIONAL YOUTH SERVICE CORPS (NYSC),1.503993e+11,12500.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12503,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.404668e+11,13300.00,NaN
12504,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.503991e+11,1.00,NaN
12505,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.504338e+11,11970.00,NaN
12506,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.504404e+11,6650.00,NaN
12507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.504621e+11,7980.00,NaN

In [14]:
merged.astype("str").to_csv("result.csv")

In [44]:
booleans = []
for i in merged.credit_difference:
    if i >= 1:
        booleans.append(True)
    else:
        booleans.append(False)

In [48]:
my_sorted = pd.Series(booleans)

In [49]:
merged[my_sorted]

c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

,loan_id,loan_principal_amount,loan_released_date,total_amount_due,balance_amount,due_date,total_paid,bvn,account_no,mandates_loandisk,borrower_firstname,borrower_lastname,borrower_email,borrower_address,mandates_bank,CREDIT,credit_difference
9,1369098.0,50000.0,24/05/2020,NaN,0.0,31/05/2020,62500.0,2.225232e+10,3.589830e+08,2.003992e+11,samaila,shawulu,samscee2000@yahoo.com,INSTITUTE OF HUMAN VIROLOGY LTD GTE,2.003992e+11,34012.35,28487.65
21,1369110.0,30000.0,27/05/2020,NaN,0.0,31/05/2020,37500.0,2.222737e+10,3.658262e+07,2.603995e+11,OLUWATOYIN,AKINKUGBE,akinkugbetoyin6@gmail.com,NaN,2.603995e+11,10558.83,26941.17
7,1369076.0,30000.0,24/05/2020,NaN,0.0,31/05/2020,37500.0,2.223589e+10,1.003459e+09,3.403992e+11,patrick,okpaire,NaN,NATIONAL YOUTH SERVICE CORPS (NYSC),3.403992e+11,26895.93,10604.07
35,1369125.0,10000.0,6/6/2020,NaN,0.0,30/06/2020,12500.0,2.219162e+10,1.017560e+09,3.204016e+11,ugochukwu,ezeokoli,ugochimereze1985@gmail.com,NaN,3.204016e+11,2010.52,10489.48
15,1369104.0,50000.0,25/05/2020,NaN,0.0,31/05/2020,62500.0,2.218154e+10,2.003643e+09,1.503994e+11,rasaq,ogungbayi,niyi.kingmakers@yahoo.com,FEDERAL MINISTRY OF HEALTH - HQTRS,1.503994e+11,61810.19,689.81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,1369749.0,50000.0,2/7/2020,NaN,62500.0,31/07/2020,0.0,2.242285e+10,2.028979e+09,NaN,arumobebi,afagha,afaghajoe@gmail.com,NIGERIA SOCIAL INSURANCE TRUST FUND,NaN,NaN,NaN
62,1369754.0,10000.0,7/7/2020,NaN,12500.0,31/07/2020,0.0,2.231424e+10,3.723681e+07,NaN,babawuro,garba,isuwa_steven@yahoo.com,FEDERAL COLLEGE OF FRESH WATER FISHERIES - BAGA,NaN,NaN,NaN
63,1369755.0,10000.0,7/7/2020,NaN,12500.0,31/07/2020,0.0,2.231424e+10,3.723681e+07,NaN,babawuro,garba,isuwa_steven@yahoo.com,FEDERAL COLLEGE OF FRESH WATER FISHERIES - BAGA,NaN,NaN,NaN
64,1369756.0,10000.0,7/7/2020,NaN,12500.0,31/07/2020,0.0,2.231424e+10,3.723681e+07,NaN,babawuro,garba,isuwa_steven@yahoo.com,FEDERAL COLLEGE OF FRESH WATER FISHERIES - BAGA,NaN,NaN,NaN
69,1369157.0,10000.0,6/6/2020,NaN,0.0,30/06/2020,12500.0,2.215860e+10,2.224398e+08,1.004016e+11,adeola,arogundade,NaN,NIGERIAN POSTAL SERVICE PLC,NaN,NaN,NaN

In [21]:
merged.groupby("loan_id")
total_merged = merged.sort_values("credit_difference", ascending = False)

In [22]:
merged = total_merged

In [31]:
filtered_merged = merged["credit_difference"] > 0

In [32]:
mergedxx = merged[filtered_merged]

In [33]:
mergedxx

,loan_id,loan_principal_amount,loan_released_date,total_amount_due,balance_amount,due_date,total_paid,bvn,account_no,mandates_loandisk,borrower_firstname,borrower_lastname,borrower_email,borrower_address,mandates_bank,CREDIT,credit_difference
792,1390893.0,94000.0,27/07/2020,NaN,0.00,31/07/2020,117500.00,2.216869e+10,4.020657e+09,1.904105e+11,baba,adamu,babajabdo18@gmail.com,NATIONAL AGRICULTURE SEEDS COUNCIL,1.904105e+11,69650.71,4.784929e+04
4144,1692669.0,32000.0,1/1/2021,NaN,0.00,1/2/2021,42560.00,2.235785e+10,7.245375e+08,2.504454e+11,farouk,isah,NaN,NATIONAL YOUTH SERVICE CORPS (NYSC),2.504454e+11,4156.96,3.840304e+04
1955,1549470.0,39000.0,5/11/2020,NaN,0.00,5/12/2020,50700.00,2.227678e+10,2.003365e+09,3.404290e+11,hussaini,isa,hamidumohammed89@gmail.com,NIGER STATE GOVERNMENT,3.404290e+11,12426.46,3.827354e+04
266,1369371.0,35000.0,23/06/2020,NaN,0.00,30/06/2020,43750.00,2.226412e+10,2.574111e+07,2.704032e+11,nuru,muhammad,NaN,"REVENUE MOBILIZATION, ALLOCATION, AND FISCAL C...",2.704032e+11,14195.70,2.955430e+04
701,1387357.0,44000.0,24/07/2020,NaN,0.00,31/07/2020,55000.00,2.234118e+10,2.024494e+09,1.604090e+11,abdulkareem,sanni,abdulkareemsannis@gmail.com,NIGER STATE GOVERNMENT,1.604090e+11,25829.82,2.917018e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452,1369559.0,10000.0,5/7/2020,NaN,0.00,31/07/2020,12500.00,2.216604e+10,3.070023e+09,2.204062e+11,amos,soko,NaN,NIGERIAN RAILWAY CORPORATION- 022900300100,2.204062e+11,12473.64,2.636000e+01
6806,1802518.0,3000.0,17/02/2021,NaN,-10.00,17/03/2021,4000.00,2.218210e+10,5.720800e+04,1.204593e+11,abdul,tela,NaN,NATIONAL COMMISSION FOR MUSEUMS AND MONUMENTS,1.204593e+11,3990.00,1.000000e+01
1972,1549487.0,35000.0,5/11/2020,NaN,0.00,5/12/2020,45500.00,2.224867e+10,2.682014e+09,3.504291e+11,nuhu,daniya,georgedaiya@yahoo.com,ZENITH BANK PLC,3.504291e+11,45500.00,7.275958e-12
5307,1758904.0,4000.0,28/01/2021,NaN,652.11,28/02/2021,4667.89,2.234796e+10,2.084662e+09,3.304537e+11,ikechukwu,nwakwuribe,NaN,NIGERIAN RAILWAY CORPORATION- 022900300100,3.304537e+11,4667.89,9.094947e-13
4733,1710241.0,10000.0,12/1/2021,NaN,8746.95,12/2/2021,4553.05,2.214984e+10,2.056499e+09,1.604471e+11,isiaq,anofi,NaN,NIGERIAN RAILWAY CORPORATION- 022900300100,1.604471e+11,4553.05,9.094947e-13

In [35]:
mergedxx.iloc["credit_difference"]

TypeError: Cannot index by location index with a non-integer key